GET http://localhost:3001/todos


### 
POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Get the bread chicken"
}

### 
DELETE http://localhost:3001/todo/delete/64d8d1732eeb727f615ec79c

###
PUT http://localhost:3001/todo/complete/64d9a8a7aa2a680ffd19c9a5